SubCategoryTable:
  Type: AWS::DynamoDB::Table
  Properties:
    TableName: SubCategoryTable-${self:provider.stage}
    BillingMode: PAY_PER_REQUEST
    AttributeDefinitions:
      - AttributeName: id
        AttributeType: S
      - AttributeName: idCategory
        AttributeType: S
    KeySchema:
      - AttributeName: id
        KeyType: HASH
    GlobalSecondaryIndexes:
      - IndexName: category
        KeySchema:
          - AttributeName: idCategory
            KeyType: HASH
        Projection:
          ProjectionType: ALL
            