service:
  name: api

plugins:
  - serverless-bundle
  - serverless-pseudo-parameters

provider:
  name: aws
  runtime: nodejs12.x
  memorySize: 256
  region: us-east-1
  stage: ${opt:stage, 'dev'}
  environment:
    CATEGORY_TABLE_NAME: ${self:custom.CategoryTable.name}
    SUB_CATEGORY_TABLE_NAME: ${self:custom.SubCategoryTable.name}
  iamRoleStatements:
    - ${file(iam/CategoryTableIAM.yml):CategoryTableIAM}
    - ${file(iam/SubCategoryTableIAM.yml):SubCategoryTableIAM}

resources:
  Resources:
    CategoryTable: ${file(resources/CategoryTable.yml):CategoryTable}
    SubCategoryTable: ${file(resources/SubCategoryTable.yml):SubCategoryTable}
  
functions:
  createCategory:
    handler: src/routes/category/createCategory.handler
    events:
      - http:
          method: POST
          path: /category
          cors: true
  updateCategory:
    handler: src/routes/category/updateCategory.handler
    events:
      - http:
          method: PUT
          path: /category/{id}
          cors: true
  getCategories:
    handler: src/routes/category/getCategories.handler
    events:
      - http:
          method: GET
          path: /categories
          cors: true
  getCategory:
    handler: src/routes/category/getCategory.handler
    events:
      - http:
          method: GET
          path: /category/{id}
          cors: true
  deleteCategory:
    handler: src/routes/category/deleteCategoy.handler
    events:
      - http:
          method: DELETE
          path: /category/{id}
          cors: true
  getSubCategory:
    handler: src/routes/subCategory/getSubCategory.handler
    events:
      - http:
          method: GET
          path: /subcategory/{id}
          cors: true
  createSubCategory:
    handler: src/routes/subCategory/createSubCategory.handler
    events:
      - http:
          method: POST
          path: /subcategory
          cors: true
  updateSubCategory:
    handler: src/routes/subCategory/updateSubCategory.handler
    events:
      - http:
          method: PUT
          path: /subcategory/{id}
          cors: true
  getSubCategories:
    handler: src/routes/subCategory/getSubCategories.handler
    events:
      - http:
          method: GET
          path: /subcategory
          cors: true
  deleteSubCategory:
    handler: src/routes/subCategory/deleteSubCategory.handler
    events:
      - http:
          method: DELETE
          path: /subcategory/{id}
          cors: true
  getAllCategoryAndSubCategory:
    handler: src/routes/categoryAndSubCategory/getAllCategoryAndSubCategory.handler
    events:
      - http:
          method: GET
          path: /categoryandsubcategory
          cors: true
          
custom:
  authorizer: arn:aws:lambda:#{AWS::Region}:#{AWS::AccountId}:function:auth-service-${self:provider.stage}-auth
  CategoryTable:
    name: !Ref CategoryTable
    arn: !GetAtt CategoryTable.Arn
  SubCategoryTable:
    name: !Ref SubCategoryTable
    arn: !GetAtt SubCategoryTable.Arn
  bundle:
    linting: false